### ISSUE TITLE
Possible to buy tickets with this package?

### ISSUE THREAD

**Issue by vdvcoder** [dcblogdev/laravel-eventbrite#1]
Hello,

Is it possible to buy an eventbride ticket with this package?
Want to setup this package for a project that would want to sell tickets with eventbride. 
They want a website where eventbride is synced with api and possibility to buy tickets through the website with eventbride.

Thanks in advance and sorry but there was no discussions tab.

**Comment by dcblogdev** [comment]
no, I don't think the Eventbrite API offers this ability
